import '../../base/styles/base.css'
import './loading.css'
import './loading-four-blue.css'
import './loading-four-white.css'
import './loading-img.css'
import './loading-ring.css'
import './loading-smile.css'