import '../../base/styles/'
import './checkbox.css'
import './checkbox-bordered.css'
import './checkbox-filled-in.css'
import './input-date.css'
import './input-has-error.css'
import './input-label.css'
import './input-line.css'
import './input-require.css'
import './input-select-group.css'
import './input-textarea.css'
import './input.css'
import './radio.css'
import './radio-filled-in.css'
import './radio-with-gap.css'
import './select.css'
import './switch.css'
import './switch-two.css'
// import './upload-btn.css'
// import './upload-card.css'

